config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end



# list_bookmarks POST   /lists/:list_id/bookmarks(.:format)
# bookmarks#create
# new_list_bookmark GET    /lists/:list_id/bookmarks/new(.:format)
# bookmarks#new
# lists GET    /lists(.:format)
# lists#index
#     POST   /lists(.:format)
# lists#create
# new_list GET    /lists/new(.:format)
# lists#new
# edit_list GET    /lists/:id/edit(.:format)
# lists#edit
# list GET    /lists/:id(.:format)
# lists#show
#     PATCH  /lists/:id(.:format)
# lists#update
#     PUT    /lists/:id(.:format)
# lists#update
#     DELETE /lists/:id(.:format)
# lists#destroy
# bookmark DELETE /bookmarks/:id(.:format)
# bookmarks#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6}
  validates :movie, uniqueness: { scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    validates :title, presence: true
    validates :title, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    
    def new
        @bookmark = Bookmark.new

    end 

    def create
       @bookmark = Bookmark.new(bookmark_params)
       @bookmark.list_id = params[:list_id]
       if @bookmark.save
            redirect_to list_path(@bookmark.list)
       else
        render :new
       end
      end

      def destroy
        @bookmark = Bookmark.find(params[:id])
        @bookmark.destroy
        redirect_to bookmark_path
      end

private 
     
      def bookmark_params
        params.require(:bookmark).permit(:comment, :movie_id)
      end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        @list = List.all
    end
    
    def show
        @list = List.find(params[:id])
    end
    
    
    def new
        @list = List.new
    end 


    def create
        @list = List.new(list_params)
        if @list.save
            redirect_to list_path(@list)
        else 
            render :new
    end

    # def update
    #     if @list.update(list_params) 
    # end

end


private 

    # Use callbacks to share common setup or constraints between actions.
    # def set_movies
    #     @movies = movies.find(params[:id])
    #   end
  
      # Only allow a list of trusted parameters through.
      def list_params
        params.require(:list).permit(:name)
      
      end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
    end

    def show
    end

    def new 
    end

    def edit
    end 




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%# nav bar start %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1563381013529-1c922c80ac8d?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=813" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>




<%# navbar end %>

<%# banner start! %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1616530940355-351fabd9524b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80);">
  <div class="container">
    <h1>Curate your own <strong>custom movie lists</strong> !</h1>
    <p>Share them with friends and family.</p>
     <%= link_to "Create a new list!", new_list_path, class: "btn btn-ghost" %>
  </div>
</div>


<%# banner end! %>

<%# list start! %>
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Create Movie Lists!</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-ghost" %>
  </div>
  <div class="row">
    <% @list.each do |list| %>
      <div class="co-12 col-sm-6 col-md-4">
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path("list_background.jpg") %>)">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%# 
<h1> Create a new list </h1>

<%= simple_form_for [ @list ] do |f| %>
  <%# <%= f.input :name %>
  <%# <%= f.submit "Submit list name", class: "btn btn-primary" %>
<%# <% end %> 


<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<h1> <strong> List Name: </strong> <%=  @list.name %> </h1>

<%= link_to "Back to all lists", lists_path %>